apiVersion: v1
kind: Namespace
metadata:
  name: px-demo-gotracing
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gotracing
  namespace: px-demo-gotracing
spec:
  selector:
    matchLabels:
      app: gotracing
  template:
    metadata:
      labels:
        app: gotracing
    spec:
      containers:
      - name: app
        # NOTE: If you create a new image this line needs to be updated:
        image: gcr.io/pixie-prod/pixie-prod-artifacts/demos/simple-gotracing-example:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: gotracing-svc
  namespace: px-demo-gotracing
spec:
  selector:
    app: gotracing
  ports:
  - port: 9090
